### PR TITLE
Fix uninitialized memory accesses

### PR DESCRIPTION
**Pull request by musicinmybrain**
Each commit fixes a warning on GCC 11.2.1 with `-Wmaybe-uninitialized`.

### CODE REVIEW

**Comment by ctlee** [comment]
Fixed in 52f105bf7407e90c8bef10cce2a41b7efcb21679

- Moved the loop to initialize `level_count` first
- Added an assertion to ensure that `i==n` at the end of `get_name`

**Comment by musicinmybrain** [comment]
> Fixed in [52f105b](https://github.com/ctlee/casc/commit/52f105bf7407e90c8bef10cce2a41b7efcb21679)

Looks good, thanks!

I haven’t taken the time to understand the big picture of this data structure. I do notice that, in the updated version of the default constructor, the value of `level_count[0]` will be `1`, whereas in the original version it would have been `0` (assuming nothing horrible happened due to undefined behavior). I point that out just in case it’s not as expected.

**Comment by ctlee** [comment]
The current behavior where `level_count[0]` is `1` after root node addition is the expected behavior. The previous behavior was a bug. Thanks again for finding it.

**Comment by musicinmybrain** [comment]
You’re welcome. I’m glad this was helpful.

**Pull request closed without merging**
